### ISSUE TITLE
Pelispedia: Link not found

### ISSUE THREAD

**Issue by Bejab** [Stormunblessed/stormunblessed-cs3#1]
Every time I choose a movie/series chapter, it shows: Link not found.

I wish they would fix it because they are a very good provider, I would really appreciate it.

https://user-images.githubusercontent.com/69412729/212738516-fe9a0757-2bc8-422a-a8a0-5a68d5431d08.mp4

**Comment by Stormunblessed** [comment]
I already fixed this, make sure you're using the [beta release](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)
