### ISSUE TITLE
Animefenix not working

### ISSUE THREAD

**Issue by N0tvich** [Stormunblessed/stormunblessed-cs3#2]
![Screenshot_2023-01-23-00-23-40-581_com lagradost cloudstream3 prerelease](https://user-images.githubusercontent.com/72475004/213978002-9e54efda-4cc2-4839-b07b-ea50f6b1c709.jpg)

Thank you ❤️ very good work

**Comment by Stormunblessed** [comment]
> ![Screenshot_2023-01-23-00-23-40-581_com lagradost cloudstream3 prerelease](https://user-images.githubusercontent.com/72475004/213978002-9e54efda-4cc2-4839-b07b-ea50f6b1c709.jpg)
> 
> Thank you ❤️ very good work

Unfortunately, I cannot fix this, animefenix has put cloudfare in their web

**Comment by N0tvich** [comment]
> > ![Screenshot_2023-01-23-00-23-40-581_com lagradost cloudstream3 prerelease](https://user-images.githubusercontent.com/72475004/213978002-9e54efda-4cc2-4839-b07b-ea50f6b1c709.jpg)
> > Thank you ❤️ very good work
> 
> Unfortunately, I cannot fix this, animefenix has put cloudfare in their web

pues ni modo,solo la desactivare de CS3 gracias hermano por este exelente extencion para CS3 

ya haces mucho por la comunidad hispano hablante  ❤️
